# Generated by Django 5.1 on 2024-10-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_author_remove_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='blog/covers/%Y/%m/%d'),
        ),
    ]
